---
title: "Sensitiviety anlysis - symptomatic test"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning= FALSE, message= FALSE}
# Preliminaries ----

## Import libraries
library(tidyverse)
library(here)
library(glue)
library(gt)
library(gtsummary)
library(reshape2)
library(stringr)

## Import custom user functions
source(here("analysis", "lib", "custom_functions.R"))

## Create output directory
dir.create(here::here("output", "coverage"), showWarnings = FALSE, recursive=TRUE)


## Redaction threshold
threshold = 5

## Import data
data_processed <- read_rds(here::here("output", "data", "data_processed_clean.rds"))

## Remove patients no longer registered at time of treatment and format variables
data_processed_clean <- data_processed %>%
  filter(has_died == 0,
         registered_eligible == 1 | registered_treated == 1) %>%
  mutate(
    
    # Age groups
    ageband = cut(
      age,
      breaks = c(12, 30, 40, 50, 60, 70, 80, Inf),
      labels = c("12-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+"),
      right = FALSE),
    
    # Vaccination status
    vaccination_status = fct_case_when(
      vaccination_status == "Un-vaccinated" ~ "Un-vaccinated",
      vaccination_status == "Un-vaccinated (declined)" ~ "Un-vaccinated (declined)",
      vaccination_status== "One vaccination" ~ "One vaccination",
      vaccination_status == "Two vaccinations" ~ "Two vaccinations",
      vaccination_status == "Three or more vaccinations" ~ "Three or more vaccinations",
      #TRUE ~ "Unknown",
      TRUE ~ NA_character_
    )
    
  )

```


## All positive SARS-CoV-2 test records
```{r, echo = FALSE}
eligible_patients <- plyr::round_any(data_processed_clean %>% nrow(), 10)
treated_patients <- plyr::round_any(data_processed_clean %>% filter(!is.na(treatment_date)) %>% nrow(), 10)

eligible_patients
treated_patients

round(eligible_patients/treated_patients*100, digits = 2)

table(data_processed_clean$symptomatic_covid_test)

```

## Symptomatic only positive SARS-CoV-2 test records
```{r, echo = FALSE}
eligible_patients <- plyr::round_any(data_processed_clean %>% filter(symptomatic_covid_test == "Y") %>% nrow(), 10)
treated_patients <- plyr::round_any(data_processed_clean %>% filter(!is.na(treatment_date), symptomatic_covid_test == "Y") %>% nrow(), 10)

eligible_patients
treated_patients

round(eligible_patients/treated_patients*100, digits = 2)

```
